#+ endpoint_in_url: False
#+ description: 项目参与者某人的职位
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX poap: <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>
select distinct ?postname where {
    ?project foaf:name "深海软体机器智能驱动技术";
             org:hasMember ?person.
    ?person foaf:name ?_personname;
            org:holds ?post.
    ?post foaf:name ?postname.
}