#+ endpoint_in_url: False
#+ description: 项目参与者某某的研究方向
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX poap: <http://purl.org/zhejianglab/irobot-center/ontologies/poap#>
select distinct ?focusOname where {
    ?project foaf:name ?_projectName;
             org:hasMember ?person.
    ?person foaf:name ?_personName;
            poap:focusOn ?focusOn.
    ?focusOn foaf:name ?focusOname.
}