#+ endpoint_in_url: False
#+ description: 项目参与者姓名(有哪些人参与项目)
#+ defaults:
#+   - projectName: "深海软体机器智能驱动技术"



PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX org: <http://www.w3.org/ns/org#>
select ?personname where {
    ?project foaf:name ?_projectName;
             org:hasMember ?person.
    ?person foaf:name ?personname.
}